
#define SYSROOT_SUFFIX_SPEC ""
#define SYSROOT_HEADERS_SUFFIX_SPEC ""

/* Redefine the entire default search path for include files so that
   it will be generated by compiler dynamically on base of the compiler's
   binary location. */
#undef INCLUDE_DEFAULTS
#define INCLUDE_DEFAULTS                                       \
  {                                                            \
    { GPLUSPLUS_INCLUDE_DIR, "G++", 1, 1, 0 },                 \
    { GPLUSPLUS_TOOL_INCLUDE_DIR, "G++", 1, 1, 0 },            \
    { GPLUSPLUS_BACKWARD_INCLUDE_DIR, "G++", 1, 1, 0 },        \
    { GCC_INCLUDE_DIR, "GCC", 0, 0, 0 },                       \
    { TOOL_INCLUDE_DIR, "BINUTILS", 0, 0, 0 },                 \
    { "/usr/include", 0, 0, 1, 1 },                            \
    { 0, 0, 0, 0, 0 }                                          \
  }

/* Define the macro to 1 to enable changes made in the gcc.c file
   to exclude host library directories such as /lib and /libexec from the
   default search path for libraries. */
#define TARGET_SYSTEM_ROOT_RELOCATABLE_ONLY 1

/* Bring in standard linux defines */
#undef TARGET_OS_CPP_BUILTINS
#define TARGET_OS_CPP_BUILTINS()        \
    do                        \
{                       \
    builtin_define ("__uClinux__");     \
    builtin_define_std ("linux");       \
    builtin_define_std ("unix");        \
    builtin_define ("__gnu_linux__");   \
    builtin_assert ("system=linux");    \
    builtin_assert ("system=posix");    \
}                       \
while (0)


/* Target CPU builtins */
#undef TARGET_CPU_CPP_BUILTINS
#define TARGET_CPU_CPP_BUILTINS()				\
  do								\
    {								\
        builtin_define ("_BIG_ENDIAN");                         \
        builtin_define ("__MICROBLAZE__");                      \
        builtin_define ("__microblaze__");                      \
                                                                \
        builtin_assert ("cpu=microblaze");                      \
        builtin_assert ("machine=microblaze");                  \
} while (0)


/* Don't set the target flags, this is done by the linker script */
#undef LIB_SPEC
#define LIB_SPEC "-elf2flt -lc"
#undef  STARTFILE_SPEC
#define STARTFILE_SPEC \
  "crt1%O%s crti%O%s crtbegin%O%s"

#undef  ENDFILE_SPEC
#define ENDFILE_SPEC \
  "crtend%O%s crtn%O%s"

/* Use default link spec, not that specified in microblaze.h */
#undef  LINK_SPEC

